### ISSUE TITLE
The nodecg.io link isn't working

### ISSUE THREAD

**Issue by noeppi-noeppi** [codeoverflow-org/nodecg-io-docs#3]
nodecg.io only takes you to the documentation if it's used with https but the link on the repository root page is http and takes you to the main nodecg-io repository. So the link should either be https or http://nodecg.io should take you to the documentation.

**Comment by noeppi-noeppi** [comment]
Nevermind it was cached by my browser...

**Comment by joblo2213** [comment]
Could alsobe your router or your operation system that cached the dns
